#!/bin/bash

# ==============================================================================
# GITHUB ISSUE UPDATE SCRIPT: GHERKIN FORMAT, ACC CRITERIA, SPRINTS & DEPENDENCIES
# Repository: https://github.com/nileshpagar/ckad-prep-series
# ==============================================================================

set -e

if ! command -v gh &> /dev/null; then
    echo "Error: GitHub CLI (gh) is not installed."
    exit 1
fi

echo "=== 1. Creating Sprint & Estimate Labels ==="
gh label create "sprint-1" --color "0E8A16" --description "Sprint 1 (Weeks 1-2)" --force
gh label create "sprint-2" --color "1D76DB" --description "Sprint 2 (Weeks 3-4)" --force
gh label create "sprint-3" --color "FBCA04" --description "Sprint 3 (Weeks 5-6)" --force
gh label create "sprint-4" --color "5319E7" --description "Sprint 4 (Weeks 7-8)" --force

gh label create "estimate: 2pts" --color "D4C5F9" --description "2 Story Points (~4 Hours)" --force
gh label create "estimate: 3pts" --color "BFD4F2" --description "3 Story Points (~6 Hours)" --force
gh label create "estimate: 5pts" --color "FBCA04" --description "5 Story Points (~8 Hours)" --force

echo "=== 2. Updating Issues with Gherkin Format & Acceptance Criteria ==="

update_issue() {
  local search_term="$1"
  local sprint_label="$2"
  local user_story="$3"
  local acceptance_criteria="$4"
  local dependencies="$5"
  local estimate_pts="$6"

  local search_id="${search_term%%:*}"
  local issue_num
  issue_num=$(gh issue list --search "$search_term in:title" --json number --jq '.[0].number' 2>/dev/null || true)

  if [ -z "$issue_num" ] || [ "$issue_num" = "null" ]; then
    issue_num=$(gh issue list --search "$search_id in:title" --json number --jq '.[0].number' 2>/dev/null || true)
  fi

  if [ -z "$issue_num" ] || [ "$issue_num" = "null" ]; then
    issue_num=$(gh issue list --search "$search_term" --json number --jq '.[0].number' 2>/dev/null || true)
  fi

  if [ -n "$issue_num" ] && [ "$issue_num" != "null" ]; then
    echo "Updating Issue #${issue_num} ($search_term) -> ${sprint_label}..."

    new_body="### 👤 User Story (Gherkin Format)
${user_story}

---
### 📋 Acceptance Criteria
${acceptance_criteria}

---
### 🔗 Dependencies
${dependencies}

---
### ⏱️ Estimation Details
- **Sprint Assignment:** ${sprint_label}
- **Story Points:** ${estimate_pts}"

    current_body=$(gh issue view "$issue_num" --json body --jq '.body // ""' 2>/dev/null || true)
    parent_feature=$(echo "$current_body" | grep -o '\*\*Parent Feature:\*\*.*' || true)

    if [ -n "$parent_feature" ]; then
      new_body="${new_body}

---
${parent_feature}"
    fi

    gh issue edit "$issue_num" \
      --add-label "${sprint_label},estimate: ${estimate_pts}" \
      --body "$new_body"
  else
    echo "Warning: Issue matching '$search_term' not found."
  fi
}

# ------------------------------------------------------------------------------
# SPRINT 1 (Weeks 1-2)
# ------------------------------------------------------------------------------

update_issue "P1.1: Exam Setup" "sprint-1" \
"**As a** CKAD exam candidate,
**I want to** configure terminal shortcuts (\`alias k=kubectl\`) and auto-completion,
**So that** I can execute cluster commands rapidly during the timed exam." \
"\`\`\`gherkin
Given I am in the exam terminal environment
When I execute 'alias k=kubectl' and source bash completion
Then typing 'k get pods' should return active pods without command errors
And exporting do='--dry-run=client -o yaml' should generate valid YAML templates
\`\`\`" \
"None (Baseline task)" "2pts"

update_issue "P1.2: Pod Creation" "sprint-1" \
"**As a** Kubernetes developer,
**I want to** generate Pod manifests imperatively using \`kubectl run\`,
**So that** I can create application workloads in under 30 seconds." \
"\`\`\`gherkin
Given I need to deploy an Nginx pod named 'web-pod'
When I run 'kubectl run web-pod --image=nginx \$do'
Then a valid Pod manifest YAML should print to stdout
And the manifest should contain container port 80 and image 'nginx'
\`\`\`" \
"Prerequisite: P1.1 (CLI Navigation)" "2pts"

update_issue "P2.1: Multi-Container" "sprint-1" \
"**As a** cloud engineer,
**I want to** deploy multi-container Pods sharing volume storage,
**So that** helper sidecars can process log files generated by the main app." \
"\`\`\`gherkin
Given a Pod manifest with two containers sharing an 'emptyDir' volume
When the main container appends logs to '/var/log/app.log'
Then the sidecar container running 'tail -f' should output those log lines to stdout
\`\`\`" \
"Prerequisite: P1.2 (Imperative Pod Creation)" "5pts"

update_issue "P2.2: Init Containers" "sprint-1" \
"**As a** software developer,
**I want to** specify \`initContainers\` in a Pod spec,
**So that** prerequisite setup tasks complete before the main app boots." \
"\`\`\`gherkin
Given an initContainer configured to wait for a DB service endpoint
When the Pod is created in the cluster
Then the main application container must remain in 'Init:0/1' status until the initContainer exits 0
\`\`\`" \
"Prerequisite: P1.2 (Imperative Pod Creation)" "3pts"

update_issue "P2.3: Jobs & CronJobs" "sprint-1" \
"**As a** DevOps engineer,
**I want to** schedule batch workloads using Jobs and CronJobs,
**So that** non-interactive processing tasks execute reliably on schedule." \
"\`\`\`gherkin
Given a Job manifest configured with 'completions: 3' and 'parallelism: 2'
When the Job is submitted to the cluster
Then Kubernetes should launch 2 worker pods in parallel until 3 total completions succeed
\`\`\`" \
"Prerequisite: P1.2 (Imperative Pod Creation)" "3pts"

# ------------------------------------------------------------------------------
# SPRINT 2 (Weeks 3-4)
# ------------------------------------------------------------------------------

update_issue "P2.4: Persistent & Ephemeral" "sprint-2" \
"**As a** database administrator,
**I want to** bind PersistentVolumeClaims to PersistentVolumes,
**So that** application state persists beyond the Pod lifecycle." \
"\`\`\`gherkin
Given a 1Gi PersistentVolume with ReadWriteOnce access mode
When a PersistentVolumeClaim requesting 1Gi is created in the namespace
Then the PVC status should instantly transition to 'Bound' with the PV
\`\`\`" \
"Prerequisite: P2.1 (Multi-Container Pods)" "5pts"

update_issue "P3.1: ConfigMaps & Secrets" "sprint-2" \
"**As a** security conscious developer,
**I want to** inject environment settings using ConfigMaps and Secrets,
**So that** configuration values remain decoupled from container images." \
"\`\`\`gherkin
Given a ConfigMap containing 'APP_COLOR=blue' and a Secret containing 'DB_PASS'
When mounted into a Pod via 'envFrom'
Then the container process environment should display 'APP_COLOR=blue' and decoded 'DB_PASS'
\`\`\`" \
"Prerequisite: P1.2 (Pod Creation)" "3pts"

update_issue "P3.2: SecurityContexts" "sprint-2" \
"**As a** security analyst,
**I want to** restrict container privileges using \`securityContext\`,
**So that** containers cannot escalate privileges or write to the root filesystem." \
"\`\`\`gherkin
Given a Pod manifest with 'runAsUser: 1000' and 'readOnlyRootFilesystem: true'
When executed in the cluster
Then running 'whoami' inside the container should output UID 1000
And writing to root directory '/' should throw a 'Read-only file system' error
\`\`\`" \
"Prerequisite: P1.2 (Pod Creation)" "5pts"

update_issue "P3.3: Resource Quotas" "sprint-2" \
"**As a** cluster admin,
**I want to** set CPU and memory requests and limits on Pods,
**So that** applications do not starve other workloads of node resources." \
"\`\`\`gherkin
Given a Pod defined with 64Mi memory request and 128Mi limit
When container memory usage exceeds 128Mi
Then Kubernetes must terminate the container with an 'OOMKilled' status
\`\`\`" \
"Prerequisite: P1.2 (Pod Creation)" "3pts"

update_issue "P3.4: Authentication" "sprint-2" \
"**As a** system admin,
**I want to** create RBAC Roles and RoleBindings,
**So that** ServiceAccounts only possess permissions required for their task." \
"\`\`\`gherkin
Given a Role granting 'get, list' on Pod resources in namespace 'default'
When bound to ServiceAccount 'app-sa' via RoleBinding
Then 'kubectl get pods --as=system:serviceaccount:default:app-sa' should succeed
And 'kubectl delete pods --as=system:serviceaccount:default:app-sa' should return Forbidden (403)
\`\`\`" \
"Prerequisite: P3.1 (ConfigMaps & Secrets)" "5pts"

# ------------------------------------------------------------------------------
# SPRINT 3 (Weeks 5-6)
# ------------------------------------------------------------------------------

update_issue "P4.1: Services & Endpoints" "sprint-3" \
"**As a** network engineer,
**I want to** expose Pod workloads via ClusterIP and NodePort Services,
**So that** internal and external clients can access the application." \
"\`\`\`gherkin
Given a Deployment running Nginx with label 'app=web'
When a NodePort Service targeting port 80 is deployed
Then curling the node IP at NodePort '30080' should return the HTTP 200 Nginx welcome page
\`\`\`" \
"Prerequisite: P1.2 (Pod Creation)" "3pts"

update_issue "P4.2: Ingress Rules" "sprint-3" \
"**As a** web architect,
**I want to** configure HTTP path routing using an Ingress Controller,
**So that** multiple backend services can be exposed under a single IP address." \
"\`\`\`gherkin
Given an Ingress rule mapping path '/api' to 'api-service:8080'
When an HTTP request is sent to 'http://ckad.example.com/api'
Then the Ingress controller should route traffic directly to backend 'api-service'
\`\`\`" \
"Prerequisite: P4.1 (Services & Endpoints)" "5pts"

update_issue "P4.3: NetworkPolicies" "sprint-3" \
"**As a** cloud security engineer,
**I want to** enforce NetworkPolicies on pod isolation,
**So that** unauthorized pods cannot initiate connection requests." \
"\`\`\`gherkin
Given a default-deny ingress NetworkPolicy on pods labeled 'role=db'
When a pod labeled 'role=frontend' attempts to connect on port 5432
Then the connection attempt should time out
Unless explicit ingress policy permits 'role=frontend'
\`\`\`" \
"Prerequisite: P3.2 (SecurityContexts) & P4.1 (Services)" "5pts"

update_issue "P5.1: Deployments" "sprint-3" \
"**As a** release manager,
**I want to** execute zero-downtime rolling updates on Deployments,
**So that** application versions update seamlessly without dropping user requests." \
"\`\`\`gherkin
Given a Deployment running image 'nginx:1.21'
When I run 'kubectl set image deployment/web-deployment nginx=nginx:1.22'
Then 'kubectl rollout status' should show zero unavailable replicas during the update
\`\`\`" \
"Prerequisite: P1.2 (Pod Creation)" "3pts"

update_issue "P5.2: StatefulSets" "sprint-3" \
"**As a** distributed systems developer,
**I want to** deploy workloads using StatefulSets,
**So that** pods maintain unique ordinal identities (web-0, web-1) and stable storage." \
"\`\`\`gherkin
Given a StatefulSet manifest with 2 replicas
When deployed to the cluster
Then pod 'web-0' must start and reach Ready status before pod 'web-1' begins creation
\`\`\`" \
"Prerequisite: P2.4 (Volumes) & P5.1 (Deployments)" "5pts"

# ------------------------------------------------------------------------------
# SPRINT 4 (Weeks 7-8)
# ------------------------------------------------------------------------------

update_issue "P5.3: Deployment Strategies" "sprint-4" \
"**As a** software engineer,
**I want to** execute Canary releases and deploy applications via Helm,
**So that** new software releases are tested safely against a small subset of traffic." \
"\`\`\`gherkin
Given a primary Deployment (90% traffic) and a Canary Deployment (10% traffic) sharing a Service label
When 100 HTTP requests are sent to the Service
Then roughly 10 requests should hit the Canary pod target
\`\`\`" \
"Prerequisite: P5.1 (Deployments) & P4.1 (Services)" "3pts"

update_issue "P6.1: Health Checks" "sprint-4" \
"**As a** site reliability engineer,
**I want to** configure liveness and readiness probes,
**So that** unhealthy containers are automatically restarted and unready pods removed from endpoints." \
"\`\`\`gherkin
Given a Pod with a livenessProbe probing '/healthz' on port 8080
When '/healthz' returns HTTP 500 status 3 consecutive times
Then Kubernetes must kill the container and trigger a container restart
\`\`\`" \
"Prerequisite: P5.1 (Deployments)" "3pts"

update_issue "P6.2: Container Logging" "sprint-4" \
"**As a** developer,
**I want to** stream logs and attach ephemeral debug containers,
**So that** I can diagnose crashing application pods in real time." \
"\`\`\`gherkin
Given a failing multi-container pod named 'crash-pod'
When I run 'kubectl debug -it crash-pod --image=busybox -- target-exec'
Then an ephemeral container should attach allowing interactive shell debugging
\`\`\`" \
"Prerequisite: P2.1 (Multi-Container Pods)" "3pts"

update_issue "P6.3: Monitoring & Metrics" "sprint-4" \
"**As a** system admin,
**I want to** inspect CPU/Memory metrics and identify deprecated API versions,
**So that** application manifests remain compliant with modern Kubernetes releases." \
"\`\`\`gherkin
Given Metrics Server is running on the cluster
When I execute 'kubectl top pod --sort-by=memory'
Then a sorted list of pods and their active memory usage in megabytes should display
\`\`\`" \
"Prerequisite: P3.3 (Resource Limits)" "2pts"

echo "=== All 19 Issues Updated with Gherkin User Stories, Acceptance Criteria, Sprints & Dependencies! ==="